# Generated by Django 4.2.24 on 2025-09-19 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='messages',
            new_name='message',
        ),
    ]
