# jobsboard/notifications/serializers.py
from rest_framework import serializers
from .models import Notification

# ---------------------------------------------------------
# NotificationSerializer
# ---------------------------------------------------------
# Serializer for the Notification model.
# - Used for listing and retrieving notifications with all fields.
# - Marks 'id', 'user', and 'created_at' as read-only to prevent modification.
class NotificationSerializer(serializers.ModelSerializer):
    class Meta:
        model = Notification
        fields = [
            "id",
            "user",
            "title",
            "message",
            "link",
            "type",
            "is_read",
            "created_at",
        ]
        read_only_fields = ["id", "user", "created_at"]

# ---------------------------------------------------------
# NotificationCreateSerializer
# ---------------------------------------------------------
# Serializer for creating new notifications.
# - Allows creating notifications with title, message, link, and type.
# - 'id' is read-only and automatically generated by the database.
# - 'user' is not included here; should be set in the view during creation.

class NotificationCreateSerializer(serializers.ModelSerializer):
    id = serializers.IntegerField(read_only=True)

    class Meta:
        model = Notification
        fields = ["id", "title", "message", "link", "type"]
        read_only_fields = ["id"]