# Generated by Django 4.2 on 2025-09-21 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_alter_jobskill_job_alter_jobskill_skill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobViewAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_aggregates', to='jobs.job')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='JobApplicationAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('application_count', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_aggregates', to='jobs.job')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='jobviewaggregate',
            index=models.Index(fields=['job'], name='idx_job_aggregate_job'),
        ),
        migrations.AddIndex(
            model_name='jobviewaggregate',
            index=models.Index(fields=['date'], name='idx_job_aggregate_date'),
        ),
        migrations.AlterUniqueTogether(
            name='jobviewaggregate',
            unique_together={('job', 'date')},
        ),
        migrations.AddIndex(
            model_name='jobapplicationaggregate',
            index=models.Index(fields=['job'], name='idx_job_app_aggregate_job'),
        ),
        migrations.AddIndex(
            model_name='jobapplicationaggregate',
            index=models.Index(fields=['date'], name='idx_job_app_aggregate_date'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplicationaggregate',
            unique_together={('job', 'date')},
        ),
    ]
