# Generated by Django 4.2.24 on 2025-09-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user'], name='idx_payments_user_id'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='idx_payments_status'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider'], name='idx_payments_provider'),
        ),
    ]
