# Generated by Django 4.2 on 2025-09-26 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(related_name='jobs', through='jobs.JobSkill', to='jobs.skill'),
        ),
        migrations.AddIndex(
            model_name='jobskill',
            index=models.Index(fields=['job'], name='idx_job_skills_job'),
        ),
        migrations.AddIndex(
            model_name='jobskill',
            index=models.Index(fields=['skill'], name='idx_job_skills_skill'),
        ),
        migrations.AlterUniqueTogether(
            name='jobskill',
            unique_together={('job', 'skill')},
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company'], name='idx_jobs_company'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='idx_jobs_status'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['posted_date'], name='idx_jobs_posted_date'),
        ),
    ]
