# Generated by Django 4.2.24 on 2025-09-19 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobskill',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='jobskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='jobs.skill'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company'], name='idx_jobs_company'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='idx_jobs_status'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['posted_date'], name='idx_jobs_posted_date'),
        ),
        migrations.AddIndex(
            model_name='jobskill',
            index=models.Index(fields=['job'], name='idx_job_skills_job'),
        ),
        migrations.AddIndex(
            model_name='jobskill',
            index=models.Index(fields=['skill'], name='idx_job_skills_skill'),
        ),
    ]
