# Generated by Django 4.2 on 2025-09-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name'], 'verbose_name_plural': 'Skills'},
        ),
    ]
