# Generated by Django 4.2.24 on 2025-09-17 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Only .jpg, .jpeg, .png allowed. Will be cropped to 320x320.', null=True, upload_to='profile_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterUniqueTogether(
            name='userfile',
            unique_together={('user', 'file_type')},
        ),
    ]
