# Generated by Django 4.2 on 2025-09-26 18:31

import companies.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2, message='Company name must be at least 2 characters long.')])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10, message='Description must be at least 10 characters.')])),
                ('logo', models.ImageField(upload_to='company_logos/')),
                ('website', models.URLField(blank=True, null=True, validators=[companies.models.validate_https])),
                ('location', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2, message='Location must be at least 8 characters.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='companies.industry')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
