# Generated by Django 4.2.24 on 2025-09-17 12:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, message='Description must be at least 10 characters.')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2, message='Location must be at least 8 characters.')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2, message='Company name must be at least 2 characters long.')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(message='Enter a valid website URL.')]),
        ),
    ]
