# Generated by Django 4.2 on 2025-09-26 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='idx_company_name'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['industry'], name='idx_company_industry'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['owner'], name='idx_company_owner'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_company_per_owner'),
        ),
    ]
