# Generated by Django 4.2.24 on 2025-09-19 17:46

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options_alter_company_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True, validators=[companies.models.validate_https]),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='idx_company_name'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['industry'], name='idx_company_industry'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['owner'], name='idx_company_owner'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_company_per_owner'),
        ),
    ]
