# Generated by Django 4.2 on 2025-09-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationfile',
            name='file_path',
        ),
        migrations.AddField(
            model_name='applicationfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='application_files/'),
        ),
    ]
