# Generated by Django 4.2.24 on 2025-09-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_reviewed_at_application_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job'], name='idx_applications_job'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant'], name='idx_applications_applicant'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='idx_applications_status'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['reviewed_by'], name='idx_applications_reviewed_by'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applied_at'], name='idx_applications_applied_at'),
        ),
    ]
