# Generated by Django 4.2.24 on 2025-09-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_limit', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ratelimit',
            index=models.Index(fields=['user', 'action'], name='idx_rate_limits_user_action'),
        ),
    ]
