# Generated by Django 4.2 on 2025-09-26 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rate_limit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ratelimit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ratelimit',
            index=models.Index(fields=['user', 'action'], name='idx_rate_limits_user_action'),
        ),
        migrations.AlterUniqueTogether(
            name='ratelimit',
            unique_together={('user', 'action', 'period_start')},
        ),
    ]
